name = "messenger-elevenlabs-worker"
main = "src/index.ts"
compatibility_date = "2024-04-01"

[vars]
META_VERIFY_TOKEN = "my_custom_verify_token_123"
META_API = "EAAWPZAeLiOfoBSQ40MP67QK6U4EY09KxMXqrCYZBJo01Gi0kbXEnG7JaA5dWDc6qdzeg5Kb11KHihqdGFPiVoGeR8DTJrgU9AcFngSYcdM516tPSoZCdPcPBeUHeWDH7HJuG3PDMbBRCswFZCGX5s4NpWGrsyEPjrm61A9ls3ZAMKd7gwi6fEFBffaDKLSTRBZASILymsKhjdUN6oeBPg5mG8Hu6nKuNTMVCPz21BMggZDZD"
ELEVENLABS_AGENT_ID = "agent_5601m0tgt63qe8tt5q9qcnfqf5wa"
CRM_SYNC_URL = "https://next-js-eleven-labs-voiceagent.vercel.app/api/chats/save"

[durable_objects]
bindings = [
  { name = "CHAT_SESSION", class_name = "ChatSession" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatSession"]
